name: Run Checks

on:
    push:
    pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run yarn check
      run: yarn check